name: CI

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false

      matrix:
        include:

          - name: Compile requirements
            python: '3.12'
            nox_session:

